### ISSUE TITLE
Reset Question

### ISSUE THREAD

**Issue by GrantMTG** [frank-zago/nvtispflash#1]
Hi. Thank you for the great tool. Some things about the MCU confuse me with regard to reset.  Obviously we prefer RPD=1, but if not (RDP=0) you seem to have a workaround.

In the datasheet and technical reference manual I find the information on RPD confusing. Are you saying we can get timing lucky when Reset rises on power-up with respect to the other ICP pins? This is the only other information I have found (outside of the datasheet):

http://forum.nuvoton.com/viewtopic.php?f=13&t=253&sid=67c7d28ef1d5dff37882ccb60606be6f

I Just want to make sure I can recover and use my part somewhat if I set RPD=0.

**Comment by frank-zago** [comment]
Hello. 
When RPD is 0, P20 (aka the Reset pin) is just a normal pin; ie. there is no reset line. So the only way to reset the chip is to power cycle it manually. This is how my samples came.
When RPD is 1, then P20 is the reset pin, so the chip can be reset automatically by setting it high then low.
In either case, when booting, the bootloader scans the UART RX pin for up to 40ms (IIRC).  If nothing shows up, it boots normally, else it starts in ISP mode. RPD is not involved in that process.
Setting RPD to 1 is just a convenience, as long as you don't need that pin in normal operations.

**Comment by frank-zago** [comment]
The link you provided concerns the hardware programmer (ICP), which is a different interface.

**Comment by GrantMTG** [comment]
Thank you! I am just trying to understand the operation so far. I'm actually using a 14-pin TSSOP at the moment and on this chip (MS51DA9AE) the RxD pin is on nReset. I think I will just get a TSSOP 20 pin part and leave nReset as it is.
